const fs = require('fs');
const path = require('path');

// --- Load data files (generated by agent workflow, see SKILL.md) ---
const shelfData = JSON.parse(fs.readFileSync(path.join(__dirname, 'my-shelf-cache.json'), 'utf8'));
const readdata = JSON.parse(fs.readFileSync(path.join(__dirname, 'my-readdata-cache.json'), 'utf8'));
const profile = JSON.parse(fs.readFileSync(path.join(__dirname, 'my-profile-cache.json'), 'utf8'));

// --- Build stats from API data + LLM-generated profile ---
function parseReadStat(readStat, name) {
  const item = readStat.find(s => s.stat === name);
  return item ? parseInt(item.counts) || 0 : 0;
}

const stats = {
  totalReadTime: readdata.totalReadTime, // seconds
  totalRead: parseReadStat(readdata.readStat || [], '读过'),
  totalFinished: parseReadStat(readdata.readStat || [], '读完'),
  readDays: readdata.readDays,
  totalNotes: parseReadStat(readdata.readStat || [], '笔记'),
  registTime: new Date(readdata.registTime * 1000).toISOString().slice(0, 7), // YYYY-MM
  preferAuthors: (readdata.preferAuthor || []).slice(0, 7).map(a => ({
    name: a.name,
    count: a.count,
    readTime: a.readTime,
  })),
  // LLM-generated fields
  tags: profile.tags,
  oneLiner: profile.oneLiner,
};

// Compute category stats
const categoryMap = {};
shelfData.books.forEach(b => {
  const parent = (b.category || '未分类').split('-')[0];
  categoryMap[parent] = (categoryMap[parent] || 0) + 1;
});
const categories = Object.entries(categoryMap).sort((a, b) => b[1] - a[1]);

// Sort books by readUpdateTime descending for initial render
shelfData.books.sort((a, b) => (b.readUpdateTime || 0) - (a.readUpdateTime || 0));

// Category color palette
const categoryColors = {
  '精品小说': '#e8927c',
  '文学': '#7cb5e8',
  '历史': '#c9a96e',
  '社会文化': '#8bc78b',
  '哲学宗教': '#b088c9',
  '政治军事': '#e87c7c',
  '经济理财': '#7ce8c9',
  '科学技术': '#c9c96e',
  '人物传记': '#e8b87c',
  '艺术': '#c97cb0',
  '童书': '#7ce89e',
  '未分类': '#aaa',
};

function getCategoryColor(cat) {
  const parent = cat.split('-')[0];
  return categoryColors[parent] || '#aaa';
}

function formatHours(seconds) {
  const h = Math.floor(seconds / 3600);
  return `${h.toLocaleString()}`;
}

const html = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>我的读书画像</title>
<style>
* { margin: 0; padding: 0; box-sizing: border-box; }

:root {
  --bg: #faf8f5;
  --text: #2c2c2c;
  --text-light: #6b6b6b;
  --accent: #c9a96e;
  --card-bg: #fff;
  --border: #e8e4df;
}

body {
  font-family: "Noto Serif SC", "Source Han Serif CN", "STSong", Georgia, serif;
  background: var(--bg);
  color: var(--text);
  line-height: 1.8;
  min-height: 100vh;
}

.view-toggle {
  position: fixed;
  top: 20px;
  right: 20px;
  z-index: 100;
  display: flex;
  gap: 8px;
}

.view-toggle button {
  padding: 8px 16px;
  border: 1px solid var(--border);
  background: var(--card-bg);
  border-radius: 20px;
  cursor: pointer;
  font-size: 13px;
  font-family: inherit;
  color: var(--text-light);
  transition: all 0.3s;
}

.view-toggle button.active {
  background: var(--text);
  color: #fff;
  border-color: var(--text);
}

/* === MINIMAL VIEW === */
.view-minimal { display: block; }
.view-wall { display: none; }
body.show-wall .view-minimal { display: none; }
body.show-wall .view-wall { display: block; }

.hero {
  max-width: 680px;
  margin: 0 auto;
  padding: 120px 40px 80px;
  text-align: center;
}

.hero h1 {
  font-size: 2.4rem;
  font-weight: 400;
  letter-spacing: 4px;
  margin-bottom: 16px;
}

.hero .subtitle {
  color: var(--text-light);
  font-size: 1rem;
  margin-bottom: 60px;
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 0;
  border-top: 1px solid var(--border);
  border-bottom: 1px solid var(--border);
  padding: 40px 0;
  margin-bottom: 80px;
}

.stat-item {
  text-align: center;
}

.stat-item .number {
  font-size: 2.2rem;
  font-weight: 300;
  color: var(--text);
  font-family: "DIN Alternate", "Helvetica Neue", sans-serif;
}

.stat-item .label {
  font-size: 0.8rem;
  color: var(--text-light);
  margin-top: 4px;
  letter-spacing: 2px;
}

.section {
  max-width: 680px;
  margin: 0 auto;
  padding: 0 40px 80px;
}

.section-title {
  font-size: 0.85rem;
  letter-spacing: 4px;
  color: var(--text-light);
  text-transform: uppercase;
  margin-bottom: 32px;
  padding-bottom: 12px;
  border-bottom: 1px solid var(--border);
}

.one-liner {
  font-size: 1.2rem;
  line-height: 2;
  margin-bottom: 40px;
  text-indent: 2em;
}

.tags {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  margin-bottom: 60px;
}

.tags span {
  padding: 6px 18px;
  border: 1px solid var(--border);
  border-radius: 20px;
  font-size: 0.85rem;
  color: var(--text-light);
}

.category-bars {
  margin-bottom: 40px;
}

.cat-bar {
  display: flex;
  align-items: center;
  margin-bottom: 12px;
}

.cat-bar .cat-name {
  width: 80px;
  font-size: 0.8rem;
  color: var(--text-light);
  text-align: right;
  padding-right: 16px;
  flex-shrink: 0;
}

.cat-bar .bar-wrap {
  flex: 1;
  height: 24px;
  background: var(--border);
  border-radius: 4px;
  overflow: hidden;
}

.cat-bar .bar-fill {
  height: 100%;
  border-radius: 4px;
  transition: width 1s ease;
}

.cat-bar .cat-count {
  width: 40px;
  font-size: 0.75rem;
  color: var(--text-light);
  padding-left: 12px;
}

.author-list {
  list-style: none;
}

.author-list li {
  display: flex;
  justify-content: space-between;
  padding: 16px 0;
  border-bottom: 1px solid var(--border);
  font-size: 0.95rem;
}

.author-list li .author-name {
  font-weight: 500;
}

.author-list li .author-meta {
  color: var(--text-light);
  font-size: 0.8rem;
}

/* === WALL VIEW === */
.wall-header {
  text-align: center;
  padding: 80px 40px 40px;
}

.wall-header h2 {
  font-size: 1.6rem;
  font-weight: 400;
  letter-spacing: 2px;
}

.wall-header p {
  color: var(--text-light);
  font-size: 0.9rem;
  margin-top: 8px;
}

.sort-toggle {
  display: flex;
  justify-content: center;
  gap: 8px;
  margin-top: 16px;
}

.sort-toggle button {
  padding: 6px 14px;
  border: 1px solid var(--border);
  background: var(--card-bg);
  border-radius: 16px;
  cursor: pointer;
  font-size: 12px;
  font-family: inherit;
  color: var(--text-light);
  transition: all 0.3s;
}

.sort-toggle button.active {
  background: var(--text);
  color: #fff;
  border-color: var(--text);
}

.book-wall {
  display: grid;
  grid-template-columns: repeat(8, 1fr);
  gap: 10px;
  padding: 20px 40px 80px;
  max-width: 1200px;
  margin: 0 auto;
}

@media (max-width: 900px) { .book-wall { grid-template-columns: repeat(5, 1fr); } }
@media (max-width: 600px) { .book-wall { grid-template-columns: repeat(3, 1fr); padding: 20px 16px; } }

.book-card {
  margin-bottom: 0;
  border-radius: 6px;
  overflow: hidden;
  background: var(--card-bg);
  box-shadow: 0 1px 4px rgba(0,0,0,0.06);
  transition: transform 0.2s, box-shadow 0.2s;
}

.book-card:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0,0,0,0.1);
}

.book-card .card-cover img {
  width: 100%;
  display: block;
  border-radius: 8px 8px 0 0;
}

.book-card .card-color {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 24px 16px;
  min-height: 100px;
}

.book-card .card-color .card-title {
  color: rgba(255,255,255,0.95);
  font-size: 0.95rem;
  text-align: center;
  line-height: 1.6;
  font-weight: 500;
  text-shadow: 0 1px 3px rgba(0,0,0,0.2);
}

.book-card .card-info {
  padding: 6px 8px 8px;
}

.book-card .card-info .card-author {
  font-size: 0.65rem;
  color: var(--text-light);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.footer {
  text-align: center;
  padding: 40px;
  color: var(--text-light);
  font-size: 0.75rem;
  letter-spacing: 1px;
}

@media (max-width: 600px) {
  .hero { padding: 80px 24px 60px; }
  .hero h1 { font-size: 1.8rem; }
  .stats-grid { grid-template-columns: repeat(2, 1fr); gap: 24px; }
  .stat-item .number { font-size: 1.6rem; }
  .section { padding: 0 24px 60px; }
}
</style>
</head>
<body>

<div class="view-toggle">
  <button class="active" onclick="toggleView('minimal')">读书画像</button>
  <button onclick="toggleView('wall')">书架墙</button>
</div>

<!-- MINIMAL VIEW -->
<div class="view-minimal">
  <div class="hero">
    <h1>我的读书画像</h1>
    <p class="subtitle">微信读书 · ${stats.registTime} 至今</p>
    <div class="stats-grid">
      <div class="stat-item">
        <div class="number">${formatHours(stats.totalReadTime)}</div>
        <div class="label">小时</div>
      </div>
      <div class="stat-item">
        <div class="number">${stats.totalRead}</div>
        <div class="label">读过</div>
      </div>
      <div class="stat-item">
        <div class="number">${stats.totalFinished}</div>
        <div class="label">读完</div>
      </div>
      <div class="stat-item">
        <div class="number">${stats.readDays}</div>
        <div class="label">天</div>
      </div>
    </div>
  </div>

  <div class="section">
    <div class="section-title">关于我</div>
    <p class="one-liner">${stats.oneLiner}。</p>
    <div class="tags">
      ${stats.tags.map(t => `<span>${t}</span>`).join('\n      ')}
    </div>
  </div>

  <div class="section">
    <div class="section-title">阅读偏好</div>
    <div class="category-bars">
      ${categories.slice(0, 8).map(([cat, count]) => {
        const pct = Math.round((count / shelfData.books.length) * 100);
        const color = categoryColors[cat] || '#aaa';
        return `<div class="cat-bar">
        <span class="cat-name">${cat}</span>
        <div class="bar-wrap"><div class="bar-fill" style="width:${pct}%;background:${color}"></div></div>
        <span class="cat-count">${count}</span>
      </div>`;
      }).join('\n      ')}
    </div>
  </div>

  <div class="section">
    <div class="section-title">偏爱作者</div>
    <ul class="author-list">
      ${stats.preferAuthors.map(a => `<li><span class="author-name">${a.name}</span><span class="author-meta">${a.count}本 · ${a.readTime}</span></li>`).join('\n      ')}
    </ul>
  </div>
</div>

<!-- WALL VIEW -->
<div class="view-wall">
  <div class="wall-header">
    <h2>书架墙</h2>
    <p>${shelfData.books.length} 本书</p>
    <div class="sort-toggle">
      <button class="active" onclick="sortWall('default')">按时间</button>
      <button onclick="sortWall('category')">按分类</button>
      <button onclick="sortWall('author')">按作者</button>
    </div>
  </div>
  <div class="book-wall">
    ${shelfData.books.map(b => {
      const color = getCategoryColor(b.category || '');
      const cat = (b.category || '未分类').replace(/'/g, '&#39;');
      const author = (b.author || '未知').replace(/'/g, '&#39;');
      const time = b.readUpdateTime || 0;
      if (b.cover) {
        return `<div class="book-card" data-category="${cat}" data-author="${author}" data-time="${time}">
      <div class="card-cover"><img src="${b.cover}" alt="${b.title}" loading="lazy"></div>
      <div class="card-info">
        <div class="card-author">${b.author || ''}</div>
      </div>
    </div>`;
      } else {
        return `<div class="book-card" data-category="${cat}" data-author="${author}" data-time="${time}">
      <div class="card-color" style="background:${color};min-height:140px">
        <span class="card-title">${b.title.length > 12 ? b.title.slice(0, 12) + '…' : b.title}</span>
      </div>
      <div class="card-info">
        <div class="card-author">${b.author || ''}</div>
      </div>
    </div>`;
      }
    }).join('\n    ')}
  </div>
</div>

<div class="footer">
  Generated on ${new Date().toISOString().split('T')[0]} · 数据来自微信读书
</div>

<script>
function toggleView(view) {
  document.body.classList.toggle('show-wall', view === 'wall');
  document.querySelectorAll('.view-toggle button').forEach(btn => {
    btn.classList.toggle('active', btn.textContent.includes(view === 'wall' ? '书架' : '画像'));
  });
}

function sortWall(mode) {
  const wall = document.querySelector('.book-wall');
  const cards = Array.from(wall.querySelectorAll('.book-card'));
  cards.sort((a, b) => {
    if (mode === 'category') return a.dataset.category.localeCompare(b.dataset.category, 'zh');
    if (mode === 'author') return a.dataset.author.localeCompare(b.dataset.author, 'zh');
    return Number(b.dataset.time) - Number(a.dataset.time); // default: newest first
  });
  cards.forEach(c => wall.appendChild(c));
  document.querySelectorAll('.sort-toggle button').forEach(btn => {
    btn.classList.toggle('active', btn.textContent.includes(mode === 'category' ? '分类' : mode === 'author' ? '作者' : '时间'));
  });
}
</script>
</body>
</html>`;

const outPath = path.join(__dirname, 'reading-profile.html');
fs.writeFileSync(outPath, html);
console.log('Generated:', outPath);
